name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gladvent = ">= 2.2.1 and < 3.0.0"
iv = ">= 1.3.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2025]
1 = { pt_1 = 3, pt_2 = 6 }
2 = { pt_1 = 1227775554, pt_2 = 4174379265 }
3 = { pt_1 = 357, pt_2 = 3121910778619 }
4 = { pt_1 = 13, pt_2 = 0 }
